### PR TITLE
add example of how to get a unique breadcrumb path for shared content

### PR DESCRIPTION
**Pull request by mojavelinux**
This PR demonstrates how to get a unique breadcrumb path for pages with common content.

### CODE REVIEW

**Comment by mojavelinux** [comment]
A note about the other changes in the PR:

* The site URL should not have a trailing slash (see https://docs.antora.org/antora/2.3/playbook/site-url/#url-key)
* The url of a local content source must point to the directory where the .git directory is located
* The branch for a local / author playbook should almost always be HEAD. That way, it follows whatever branch you are currently on and you don't need multiple author playbooks.

**Comment by mojavelinux** [comment]
In summary, the page filename must be unique. The page content does not have to be.

**Review by cortizqgithub — APPROVED** [review]
All of these changes are what I was looking for to solve my issue. I truly appreciate all of your recommendations.

Thanks, @mojavelinux

**Comment by mojavelinux** [comment]
That's great news! I'm so glad to hear it. Glad to help.

**Pull request merged**
